version: 1
datastore:
  user: root
  password: password
  hostname: services-based-kafka.westus.cloudapp.azure.com
  port: 3306
  db: events
events:
  hostname: services-based-kafka.westus.cloudapp.azure.com
  port: 9092
  topic: events